# Generated by Django 3.2.11 on 2022-04-03 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('private_key', models.CharField(max_length=255, verbose_name='Private key')),
                ('public_key', models.CharField(max_length=255, verbose_name='Public key')),
                ('wif', models.CharField(max_length=255, verbose_name='WIF')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
    ]
